import dash
from dash import dcc, html
import dash_bootstrap_components as dbc
import os
import csv


dash.register_page(__name__,path='/khoka_glossary')

# Define the navigation bar with the dropdown menu

portada =  dbc.Row(
        [
            html.Img(src="/assets/h_glosa_1.webp",style={"width": "100%",'marginTop':'3%','marginBottom':'3   %'},className="center-image"),
        ]
                )

glosario = dbc.Container(
    dbc.Row([
                dbc.Row(className="espaciado_96_esc espaciado_96_mov"),
                html.Div("GLOSSARY", className="body-title-green"),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 

                html.Div(["Acid"],className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A substance that, when dissolved in water, produces a solution with a pH lower than 7."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Polyunsaturated Fatty Acid",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([": A type of healthy fat found in both plant and animal foods such as salmon, vegetable oils, and certain nuts and seeds. These fats, like monounsaturated fats, help reduce bad cholesterol levels and may lower the risk of heart disease."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("DNA",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Deoxyribonucleic acid, also known by the initials DNA, is a molecule that contains the genetic instructions used in the development and functioning of all living organisms and some viruses. It is fundamental for genetic inheritance."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Desiccant Agent",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A material that absorbs water from the environment, used to keep products and surroundings dry."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Alkaloid",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Natural compounds produced by plants through secondary metabolism. They contain nitrogen in their molecular structure and are known for their potent effects on the body, even in small doses. Alkaloids are used in medicine to relieve pain and treat mental illnesses. Notable examples include caffeine in coffee, nicotine in tobacco, both stimulants; cocaine from the coca plant, which is also a local anesthetic; and morphine from the poppy, used as a painkiller."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Amino Acids",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The building blocks of proteins in the body. Each amino acid is composed of an amino group (NH2) and a carboxyl group (COOH) in its molecular structure."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Essential Amino Acids",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Amino acids that the human body cannot synthesize and must therefore be obtained through the diet. There are nine essential amino acids: histidine, isoleucine, leucine, lysine, methionine, phenylalanine, threonine, tryptophan, and valine."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Non-Essential Amino Acids",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Amino acids that the human body can synthesize on its own, so it is not necessary to obtain them exclusively through the diet. Non-essential amino acids include alanine, arginine, asparagine, aspartic acid, cysteine, glutamic acid, glutamine, glycine, proline, serine, and tyrosine."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Anesthetic",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([" A drug used to induce anesthesia, resulting in reversible loss of sensation or consciousness. Anesthetics are classified into two types: general, which cause a reversible loss of consciousness, and local, which cause a reversible loss of sensation in a specific area of the body without affecting consciousness."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Atom",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The smallest particle of a chemical element that retains all its chemical properties. It consists of a positively charged nucleus containing protons and neutrons, which make up approximately 99.9% of the atom's mass. Electrons, which have a negative charge and are much lighter, orbit the nucleus and determine the atom's size."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("ATP (Adenosine Triphosphate)",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["ATP is a molecule essential for the energy metabolism of cells. It consists of three phosphate groups, a nitrogenous base called adenine, and a pentose sugar called ribose. ATP is produced in the mitochondria of animal cells and the chloroplasts of plants. This molecule acts as an energy battery for cells, providing the necessary energy for numerous enzymatic processes and chemical reactions that facilitate catalysis and other vital functions."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Nitrogenous Base",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Organic compounds with a cyclic structure that contain two or more nitrogen atoms. They are essential components of nucleosides, nucleotides, cyclic nucleotides, dinucleotides, and nucleic acids. In DNA, nitrogenous bases are represented by the letters A (adenine), T (thymine), G (guanine), and C (cytosine). These bases pair specifically (A with T and G with C) to form the double-helix structure of DNA, enabling the storage and transmission of genetic information."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Benzine",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([" A mixture of low molecular weight hydrocarbons such as pentane, hexane, and heptane. These components have boiling points ranging between 40 and 60 degrees Celsius, making benzine useful for various industrial and commercial applications."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Biosynthesis",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The process by which living organisms use enzymes to convert simple molecules into more complex ones through multiple reaction stages. This process is fundamental for forming essential biochemical compounds."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Asymmetric Carbon",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([" A carbon atom bonded to four different atoms or groups. This unique structure allows it to have optical activity, meaning it can rotate polarized light when viewed through a polarimeter. Asymmetric carbons are commonly found in sugars, amino acids, and various organic compounds. This property is essential in chemistry and biology because how these molecules interact can depend on their specific three-dimensional structure."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Carboxyl Group",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["In organic chemistry, the carboxyl group is a functional group composed of a carbon atom bonded to two oxygen atoms. One of the oxygens is double-bonded to the carbon, and the other oxygen is single-bonded to the carbon and, in turn, is attached to a hydrogen atom or another element, such as sodium or lithium. This functional group is characteristic of carboxylic acids, which are found in a variety of organic compounds essential for life, such as amino acids and fatty acids."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Coenzyme",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([" A small molecule that binds to an enzyme and is crucial for its function. It helps transfer chemical groups, electrons, or hydrogen atoms during chemical reactions in the body. Coenzymes are essential for many metabolic functions and often derive from vitamins, such as vitamin B12."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Cofactor",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(['A non-protein chemical compound or metallic ion required for an enzyme to act as a catalyst. Cofactors act as "helper molecules," facilitating biochemical transformations within the organism. Without these cofactors, many enzymes would not function correctly, affecting numerous essential biological processes. Cofactors can be metal ions like magnesium or zinc, or organic molecules known as coenzymes, such as vitamins.']),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("LDL Cholesterol",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(['Low-density lipoprotein (LDL) cholesterol, often referred to as "bad" cholesterol, is a fatty substance that can accumulate in the arteries, increasing the risk of heart disease. It is found in the blood and originates from both the liver and foods such as meat and dairy products. While the body needs some cholesterol to function, high levels of LDL can be dangerous. In contrast, high-density lipoprotein (HDL) or "good" cholesterol helps remove cholesterol from the body by transporting it to the liver.']),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Compound",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A substance formed from the chemical combination of two or more elements from the periodic table. Each compound is represented by a molecular formula indicating the exact proportion of the elements that make it up. For example, water is represented as H₂O, indicating two hydrogen atoms and one oxygen atom."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Chemical Compound",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A substance made up of two or more different elements chemically bonded together. Each compound has a specific chemical formula that indicates its composition. For example, water (H₂O) consists of two hydrogen atoms and one oxygen atom."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Cis-Trans Configuration",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A type of isomerism in molecules with carbon double bonds or cyclic rings. In the cis configuration, substituent groups are on the same side of the double bond, while in the trans configuration, they are on opposite sides. For example, maleic acid (cis) and fumaric acid (trans) have the same molecular formula (C₄H₄O₄) but different arrangements of their carboxyl groups."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Oxidative Damage",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Occurs when there is an imbalance between the production of reactive oxygen species (free radicals) and the organism's ability to neutralize them and repair the damage they cause. This imbalance is responsible for many degenerative diseases, including Parkinson's, Alzheimer's, and arteriosclerosis."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Solvent",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Also called a dissolvent, a solvent is a substance, generally a liquid, that can dissolve other substances without chemically altering them, forming a solution."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Decantation",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A separation method used to divide components of heterogeneous mixtures, particularly useful for separating liquids with different densities. This process allows the denser liquid to settle at the bottom while the less dense one remains on top, facilitating their separation."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Element",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A pure chemical substance composed exclusively of atoms with the same number of protons in their atomic nucleus, which defines its unique identity on the periodic table."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Electron",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A subatomic particle with a negative electric charge, represented by the symbol e⁻. Electrons have no detectable components or substructures, classifying them as elementary particles."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Enantiomer",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Enantiomers are compounds that are non-superimposable mirror images of each other, similar to how your left and right hands are mirror images but cannot be perfectly aligned. They have the same molecular formula but differ in spatial arrangement. This type of isomerism is called optical isomerism, and enantiomers are classified as either R (rectus) or S (sinister). Optical isomerism is detected using a polarimeter, which measures how a solution rotates polarized light. This rotation can be to the right or left and is used to determine the concentration of compounds like sugar in beverages."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Energy",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The capacity to perform work or induce physical change; it is a fundamental property of nature that manifests in various forms, such as mechanical, thermal, electrical, chemical, nuclear, and others. Energy can be transferred between systems and converted from one form to another but cannot be created or destroyed (the first law of thermodynamics)."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Enzyme",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A protein that accelerates a biochemical reaction in metabolism."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"), 
                html.Div("Exfoliant",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A product that removes dead skin cells."]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Phase",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A distinct physical state within a system characterized by uniform physical and chemical properties. It commonly refers to the different forms in which matter exists, such as solid, liquid, gas, or plasma. In a heterogeneous system, different phases are separated by clearly defined boundaries."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Photosynthesis",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Photosynthesis is the biological process by which plants, algae, and some bacteria use sunlight to convert it into chemical energy stored in sugar molecules, primarily glucose. During photosynthesis, these organisms capture carbon dioxide (CO₂) from the air and water (H₂O) from the soil, and under the influence of sunlight, they transform them into glucose and oxygen. Oxygen is released as a byproduct, vital for the respiration of most life forms on Earth. This process is fundamental not only for the survival of plants and other photosynthetic organisms but also for sustaining life on the planet by producing most of the atmospheric oxygen and forming the basis of food chains."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Gene",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The functional and physical unit of heredity that is passed from parents to offspring. Genes are specific segments of DNA located on chromosomes, and each contains the information necessary to produce specific proteins, which play essential roles in an organism's growth, development, and function. In addition to protein synthesis, some genes have regulatory roles that affect the expression of other genes, influencing cellular activity and structure without directly encoding proteins."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Methyl Group",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A molecular structure consisting of one carbon atom bonded to three hydrogen atoms, represented as CH₃-. It is found in many organic compounds and is derived from methane (CH₄), which consists of one carbon atom and four hydrogen atoms."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Immiscible",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Refers to a substance that does not mix and remains separated into distinct phases or forms a suspension."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Ion",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A particle with an electric charge, formed by an atom or molecule that has gained or lost electrons. If it has a positive charge, it is called a cation; if it has a negative charge, it is called an anion."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Isomer",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A molecule that has the same molecular formula as another but with a different arrangement of atoms. There are several types of isomers, including chain isomers (different carbon skeleton structures), positional isomers (different location of a functional group), optical isomers (different spatial orientation that affects optical activity), and configurational or cis-trans isomers (different arrangement around a double bond or ring)."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Light",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A form of electromagnetic radiation visible to the human eye. It is transmitted in waves that, when reflected from surfaces, illuminate objects and allow us to see colors. The wavelength of visible light, which is only a small part of the electromagnetic spectrum, ranges from approximately 400 nanometers (violet) to about 700 nanometers (red). Beyond these limits are ultraviolet light, which has shorter wavelengths than violet, and infrared light, which has longer wavelengths than red, both of which are invisible to the human eye."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Ultraviolet (UV) Light",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div([" Ultraviolet light is a form of electromagnetic radiation located on the spectrum between visible light and X-rays. Its wavelengths range from 100 to 400 nanometers and are invisible to the human eye. UV light primarily comes from the sun, but it can also be emitted by artificial sources like UV lamps and lasers. While it has useful applications in medicine, sterilization, and photography, prolonged exposure to UV light can have adverse health effects, such as sunburns, eye damage, and an increased risk of skin cancer due to its ability to damage cellular DNA."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Mixture",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A physical combination of two or more substances in which each component retains its individual chemical properties. The substances in a mixture do not combine chemically and can, therefore, be separated by physical means such as filtration, centrifugation, decantation, or distillation."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Homogeneous Mixture",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A type of mixture in which the components are uniformly distributed throughout and cannot be distinguished by the naked eye. Solutions like air, vinegar, or an aqueous salt solution are examples of homogeneous mixtures. At the molecular level, the mixture presents a single, continuous phase."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Heterogeneous Mixture",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A mixture in which the components can be visually identified because they are not evenly distributed. These mixtures contain two or more visible phases, each with distinct chemical properties. Common examples of heterogeneous mixtures include sand mixed with water, fruit salad, and concrete."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Miscible",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The ability of two or more substances to mix completely with each other, forming a homogeneous solution. This means that when combined, they integrate uniformly into a single phase without separating under certain conditions of temperature, pressure, and composition. A common example is alcohol and water, which form a uniform solution when mixed."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Molecule",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A defined group of two or more atoms chemically bonded together, representing the smallest unit of a pure chemical substance that retains all of its characteristic properties. Molecules can vary in size, from simple diatomic molecules like oxygen (O₂) to complex macromolecules like DNA and proteins, which consist of thousands of atoms bonded into specific structures. The bonds that hold the atoms together in a molecule can be covalent, where atoms share electrons, or ionic, where atoms are attracted to each other due to opposite charges. The structure and composition of a molecule define its physical and chemical properties."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Mole",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The mole is the unit in the International System of Units (SI) used to measure the amount of a substance. One mole is exactly equal to Avogadro's number, that is, 6.02214076×10²³ elementary entities, which may be atoms, molecules, ions, or any other basic unit that makes up a substance. This definition allows scientists to quantify and compare amounts of substances at the atomic and molecular level with precision."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Narcotic",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The term narcotic is generally used to describe substances that induce sleep, muscle relaxation, and a loss of sensitivity and consciousness. In the medical context, narcotics are a class of drugs known as opioid analgesics, primarily used for the management of severe pain. These compounds act on the central nervous system to alleviate pain but can also suppress respiration, cause drowsiness, and often lead to physical and psychological dependence if used inappropriately or over extended periods. Common examples include morphine, fentanyl, and codeine."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Neurotransmitter",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A biomolecule that transmits information between cells of the nervous system. It functions as a chemical messenger, sending signals from one neuron to another or to a muscle cell or gland through a process called synapse. Neurotransmitters are essential for communication in the brain and body and play a crucial role in functions such as movement, emotions, and thought."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Neutron",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A subatomic particle without an electric charge, located in the nucleus of almost all atoms, alongside protons. Neutrons have a slightly greater mass than protons and are neutral in charge. Their presence in the nucleus contributes to its stability, as neutrons help to reduce the electrostatic repulsion between the positively charged protons. Neutrons play a crucial role in many nuclear processes, including nuclear fission and fusion. They are also essential in particle physics and nuclear technology, such as energy generation and medical applications. A notable example is protium, the most common isotope of hydrogen, which consists of a single proton and no neutrons."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Atomic Nucleus",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The central part of the atom, where approximately 99.9% of its total mass is concentrated. It is positively charged and composed mainly of two types of subatomic particles: protons, which carry a positive charge, and neutrons, which have no charge. These particles are bound together by a strong nuclear force, which is essential for the nucleus’s stability. The number of protons in the nucleus determines the chemical element (for example, hydrogen has 1 proton, helium has 2, carbon has 6, and uranium has 92). Atoms of the same element that differ in the number of neutrons are known as isotopes, which can exhibit different physical and chemical properties, including stability and radioactivity."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Nucleotide",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Nucleotides are the basic structural and functional units that make up nucleic acids, such as DNA and RNA. Each nucleotide consists of three components: a nitrogenous base (which can be adenine (A), thymine (T), cytosine (C), or guanine (G) in DNA; in RNA, thymine is replaced by uracil (U)), a five-carbon sugar (ribose in RNA, deoxyribose in DNA), and a phosphate group. These elements are connected in specific sequences to form long chains of DNA and RNA that store and transmit genetic information essential for the development, functioning, and reproduction of living organisms."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Oxidation",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The chemical process by which an atom, ion, or molecule loses electrons during a reaction. Traditionally, this term was associated with reactions where oxygen combined with other substances, increasing the oxygen content of the compound. However, in a broader sense, oxidation does not necessarily involve oxygen. It is defined in modern chemistry as the loss of electrons, which can alter the chemical properties of the involved substance. Oxidation typically occurs simultaneously with reduction, in which another substance gains the electrons lost in the oxidation process. Together, these complementary processes are known as redox (reduction-oxidation) reactions."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Subatomic Particle",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A particle smaller than an atom, which can be either elementary or composite. Elementary particles, such as electrons, are basic components of matter that do not consist of smaller particles and have fundamental physical characteristics. On the other hand, composite particles, such as protons and neutrons, are made up of smaller particles called quarks, held together by the strong nuclear force. Subatomic particles play critical roles in the structure and behavior of atoms and, therefore, in all chemical and physical properties of matter."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Pathogen",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["An infectious agent capable of causing disease in its host. Pathogens can be of various biological natures and include viruses, bacteria, fungi, and parasites. Each type of pathogen has unique methods of invasion and replication within the host."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Molecular Weight",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["More accurately referred to as molar mass, it is a physical property that describes the mass of one mole of molecules of a substance. It is measured in grams per mole (g/mol). This measurement indicates how much one mole of any chemical substance weighs based on the sum of the atomic masses of the atoms that make up one molecule of that substance, according to the periodic table." ]),
                dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Proton",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A subatomic particle located in the nucleus of an atom that carries a positive charge. The charge of a proton is equal in magnitude but opposite in sign to that of an electron, which has a negative charge. With a mass approximately 1836 times greater than that of an electron, protons significantly contribute to the total mass of the atom. The number of protons in the atomic nucleus determines the atomic number of an element and, therefore, its chemical identity. Along with neutrons, protons in the nucleus are held together by the strong nuclear force, which is responsible for maintaining the stability of the nucleus despite the electrostatic repulsion between the positively charged protons."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Proteins",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Proteins are complex and essential macromolecules that perform a wide variety of critical functions within living organisms. They are made up of linear chains of amino acids, whose sequence is determined by the nucleotides in the corresponding genes in the DNA. These sequences of amino acids fold into specific three-dimensional structures that determine the protein's function. Proteins are indispensable for virtually all biological processes, including catalyzing metabolic reactions (enzymes), regulating gene expression, transmitting signals between and within cells, providing structural support in cells and tissues, and transporting molecules across cell membranes. Additionally, proteins play a crucial role in the immune system and in muscle movement. Because of their functional diversity and role in many diseases, they are a central focus in biomedical and biotechnological research."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Radiation",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Radiation is the emission and propagation of energy in the form of electromagnetic waves or subatomic particles traveling through space or a medium. This energy can manifest in various forms, such as visible light, radio waves, ultraviolet rays, X-rays, or gamma rays in the case of electromagnetic radiation, or as particles such as alpha, beta, and neutrons in particle radiation. Radiation can be natural, like sunlight reaching the Earth, heat emitted by the human body, or radiation from naturally occurring radioactive elements in the environment. It can also be artificial, generated by human-made devices such as X-ray machines, nuclear reactors, or radiofrequency emitters. Radiation has numerous applications in medicine, industry, research, and technology; however, excessive exposure to certain types of radiation can be harmful to living organisms, causing damage ranging from sunburns to genetic mutations and cancer."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Reduction",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Reduction is an electrochemical process in which an atom, ion, or molecule gains electrons, resulting in a decrease in its oxidation state. This process is fundamental in redox (reduction-oxidation) reactions, where reduction occurs simultaneously with oxidation, which is the loss of electrons by another species. Reduction reactions are essential in many chemical and biological processes, including photosynthesis, cellular respiration, and energy generation in batteries. More broadly, reduction can also refer to the decrease of oxygen or the increase of hydrogen in a molecule during a chemical reaction."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Free Radical",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A free radical is a highly reactive chemical species that has an unpaired electron in its outer electron shell, making it highly reactive and likely to participate in chemical reactions to achieve stability. Free radicals are typically formed as intermediates in chemical reactions through the homolytic breaking of chemical bonds, where each atom retains one of the electrons from the original bond. Although they have a very short lifespan, free radicals can initiate chain reactions that result in significant changes in molecular structures. In biology, free radicals are known for their role in oxidative stress, where accumulated damage to cells and tissues can contribute to aging and various diseases, including cancer and cardiovascular disease. Additionally, free radicals have industrial applications in polymerization, plastic manufacturing, and wastewater treatment, among others."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Sedative",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A sedative is a substance or combination of substances that exerts a relaxing effect on the central nervous system. Sedatives are commonly used to treat conditions such as anxiety and insomnia, helping to reduce tension, agitation, and facilitate sleep. These drugs can vary in potency, from mild sedatives that help relax the patient to more potent hypnotics that induce sleep."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Synthesis (Chemistry)",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Chemical synthesis is the process by which complex chemical compounds are created from simpler reactants through controlled chemical reactions. This process is fundamental in chemistry for manufacturing numerous products, from medicines to advanced materials. Chemical synthesis involves the formation of chemical bonds and is carried out following specific methods and techniques that allow obtaining the desired product with high purity and yield. It is used in both research and industry to develop new substances and improve the properties of existing ones."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Substance (Chemistry)",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A chemical substance is a form of matter that has a constant chemical composition and characteristic properties. Chemical substances can be pure elements, like oxygen or gold, where all the atoms are identical, or compounds that consist of two or more chemical elements bonded in fixed proportions. These compounds can be organic, generally containing carbon and other elements like hydrogen, oxygen, and nitrogen, which form the basis of life’s chemistry."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Solubility",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The ability of a substance, known as the solute, to dissolve in another substance, called the solvent, to form a homogeneous solution. The solubility of a solute in a particular solvent depends on factors such as temperature, pH, and environmental pressure. This property is fundamental for numerous processes in chemistry, biology, pharmacology, and daily life."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Solute",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["The substance that dissolves in another substance, known as the solvent, to form a solution. The solute is typically present in a smaller quantity within the mixture, although this can vary depending on the solution."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Solution",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A homogeneous mixture composed of a solvent and one or more solutes. In a solution, the solute completely dissolves in the solvent, resulting in a uniform composition at the molecular level."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Periodic Table",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A graphical representation of the periodic law, which states that the properties of chemical elements vary periodically as a function of their atomic numbers. The table is organized into rows called periods and columns called groups. Elements in the same group share similar chemical behaviors due to their electronic configuration. The table is divided into four main blocks, each corresponding to the electronic configuration of the last added electron: s, p, d, and f blocks. This organization helps predict relationships between the properties of elements and understand the structure of the compounds they form. Additionally, it facilitates the study of chemical and physical trends across and within the table."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Toxic",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["Refers to any substance that, when ingested, inhaled, or absorbed through the skin, can cause serious harm to the body or even death."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),
                html.Div("Xenobiotic",className="body-title-2_glosary"),
                dbc.Row(className="espaciado_24_esc espaciado_24_mov"),
                html.Div(["A xenobiotic is a chemical substance that is foreign to an organism and not naturally produced by it. These substances can include drugs, environmental pollutants, and other synthetic chemicals that may be introduced into the body through various pathways. Xenobiotics can sometimes be metabolized by the organism, although they may also cause harmful effects if they accumulate."]),
                       dbc.Row(className="espaciado_48_esc espaciado_48_mov"),



                
            ],
            className="container-text"
        ))

# Definir los tooltips
tooltips = []


# Define the layout
layout =    [ dbc.Col(
                portada,
                xs={"size": 12, "order": 2},  # Change order to 2 on extra small devices
                sm={"size": 12, "order": 2},  # Change order to 2 on small devices
                md={"size": 12, "order": 3},
                lg={"size": 12, "order": 3},
                xl={"size": 12, "order": 3},
                style={'paddingRight':'0rem','paddingLeft':'0rem'}
                
            ),
            dbc.Col(
                glosario,
                xs={"size": 12, "order": 4},  # Change order to 2 on extra small devices
                sm={"size": 12, "order": 4},  # Change order to 2 on small devices
                md={"size": 12, "order": 4},
                lg={"size": 12, "order": 4},
                xl={"size": 12, "order": 4},
                style={'paddingRight':'0rem','paddingLeft':'0rem'}
            ),
            *tooltips
        ]


